### PR TITLE
Can't use variable before its declared.

### PR DESCRIPTION
**Pull request by TheShadowGamer**
Throughout lines 28-60, you attempt to use `client.config` which you cannot use since it is not defined until later. The fix would be to move the `client.config = config` higher up, as I have done.

### CODE REVIEW

**Comment by TheShadowGamer** [comment]
Path is sometimes used, but its never installed with `npm i`. An example would be line 3 of `approve-join.js`. I have fixed that in my last commit.

**Comment by yogurtsyum** [comment]
> Path is sometimes used, but its never installed with `npm i`. An example would be line 3 of `approve-join.js`. I have fixed that in my last commit.

Because it's built into Node.js. 🙃

**Comment by TheShadowGamer** [comment]
Weird, as it errored when I tried using `require path` for something I'll PR soon. Still safe to have it in the package.json in my opinion, but that is up to you.

**Comment by yogurtsyum** [comment]
Wouldn't it be less safe? Because then you're relying on the people who have the npm package "path" to keep it 100% updated to the built in package.

**Comment by TheShadowGamer** [comment]
I suppose. I'm not sure why path would fail to require if it is built into Node.js.

**Comment by yogurtsyum** [comment]
Anyways, can you please remove it from the package.json so I can merge this pull request? Thanks.

**Comment by TheShadowGamer** [comment]
Alright will do.

**Pull request merged**
