### PR TITLE
More commands and pre-made config.json file

### PR DESCRIPTION
**Pull request by zachariapopcorn**
I added a few commands to the index.js file that include eval, suspend, and exile. I also made changes to config.json to fit changes I did to the fire command, lowest role = fired role if your wondering. I saw people wanting a suspend and exile command, so I made these, hope ya'll enjoy. Also, there's a blacklist system on there.

### CODE REVIEW

**Comment by yogurtsyum** [comment]
Hi,
Thanks for submitting your pull request. I might make a few changes to some of these features if you are okay with that, but in general this is a great head start for coding all of them.

**Comment by zachariapopcorn** [comment]
I pretty much just used the setrank and fire command, changed some value, and boom, done, lol.

**Comment by TypicallyShad** [comment]
I love that you added the ``eval`` command. It'd help allow others to explore what they can do with a little bit of JavaScript.

**Comment by yogurtsyum** [comment]
Please recreate this pull request but make it go to the `5.0-pulls` branch.

**Pull request closed without merging**
