### PR TITLE
add rowifi support

### PR DESCRIPTION
**Pull request by brandoge91**
discord user+tag: brandonn#1234
discord id: 785248634458996767

adding: verification checks for rowifi api aswell

### CODE REVIEW

**Review by IeuanGol — COMMENTED** [review]
What are the rate limits for this API?

**Comment by brandoge91** [comment]
no idea, ill ask in the support server!

**Comment by IeuanGol** [comment]
Thanks

**Comment by brandoge91** [comment]
there's no api rate limit. Proof: https://brandon.has-no-bra.in/duQ10M

**Comment by yogurtsyum** [comment]
This is a nice pull request, but I've been considering moving the function that checks if the user is verified over to my API. I will update this pull request with what I choose.

**Comment by brandoge91** [comment]
I'm bumping this PR, since i've added group-defender integration into qbot.

things to add: in the setup guide/.env make a new line called webhookurl which is where group-defender sends abuse reports. this cannot be empty.

I'm adding this since it's highly requested and would fit nicely in the huge v6 rewrite

**Comment by yogurtsyum** [comment]
I think we should code an anti abuse system from scratch instead of one that uses a npm package. It will make qbot more lightweight and will allow us to customize and integrate it more.

**Comment by yogurtsyum** [comment]
Also, in the future, I recommend you make separate pull requests for if you are adding different features. Because then we can choose to push them individually.

**Comment by TheShadowGamer** [comment]
> This is a nice pull request, but I've been considering moving the function that checks if the user is verified over to my API. I will update this pull request with what I choose.

If you did this, then I think all qbot instances would be ratelimited the same. Ex:
- group 1 runs promote
- group 2 runs promote

Now they both have a ratelimit of two, even though they each only used the command once.

**Comment by BillyH-0167** [comment]
This wouldnt work since their api returns a boolean (true /false) not a string the PR i just did should fix that.

**Review by BillyH-0167 — CHANGES_REQUESTED** [review]
Change this line 34 from :
```js


   if(rowifiJson.success === 'true') {
```

to 




```js
   if(rowifiJson.success === true) {
```

**Pull request closed without merging**
