### PR TITLE
Update on readme.md

### PR DESCRIPTION
**Pull request by TypicallyShad**
Overall, I believe the readme.md file should have been edited ages ago to attract more people and make it more clear on what qbot can do. The wiki explains how to set up the bot and such, but doesn't really explain the features or how qbot can be unique for others, therefore, I pulled this request to edit it.

When I also first came across qbot, I just skipped it as I was unsure if it was the correct thing I was looking for, I think this will be a huge benefit.

You may need to edit some stuff, like the Discord or anything else I did wrong, sorry about that.
(Reposted from request.)

### CODE REVIEW

**Comment by yogurtsyum** [comment]
Just to confirm, do you allow me to use your writing in the qbot 5.0 README file if you get credit on the repository?

**Comment by yogurtsyum** [comment]
In order to release qbot on time, I need to put this pull request into qbot 5.1 which will be released soon. Sorry for the inconvenience.

**Comment by TypicallyShad** [comment]
You can use it, I do not really need credit:

**Comment by yogurtsyum** [comment]
Hi,
I am actually going to close/deny this pull request because I feel I have to rewrite some of the README.md file. 
Thank you.

**Pull request closed without merging**
